# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LeetcodeTool < Formula
  desc "一个让你更方便刷题的工具"
  homepage "https://github.com/ppsteven/leetcode-tool"
  version "1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PPsteven/leetcode-tool/releases/download/v1.5/leetcode-tool_Darwin_x86_64.tar.gz"
      sha256 "90b40570b970e906396f0bc44c635f6c28cdbac2adf53267c89a51e936b9979d"

      def install
        bin.install "leetcode-tool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PPsteven/leetcode-tool/releases/download/v1.5/leetcode-tool_Darwin_arm64.tar.gz"
      sha256 "3865b7cd6f763801a47a3745ba91b5d801aa763851e4ce131fc6c9e2f948f308"

      def install
        bin.install "leetcode-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/PPsteven/leetcode-tool/releases/download/v1.5/leetcode-tool_Linux_x86_64.tar.gz"
      sha256 "e52917a5e79a753800ac227ef0437298566375e1a2c6da7cd7cd25a08c5419c2"

      def install
        bin.install "leetcode-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PPsteven/leetcode-tool/releases/download/v1.5/leetcode-tool_Linux_arm64.tar.gz"
      sha256 "947046d6ab27f64b2cfece7fa4c24dfd470aaecbef3136e98271e6e0d9571013"

      def install
        bin.install "leetcode-tool"
      end
    end
  end

  test do
    system "#{bin}/leetcode-tool -v"
  end
end
